# Este nome aparece na aba "Actions" do GitHub
name: Deploy to Firebase Hosting on merge

# Aciona a automação quando houver um push para a branch 'main'
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do seu repositório para o ambiente de automação
      - uses: actions/checkout@v4

      # 2. Instala as dependências e COMPILA o projeto
      # AQUI ESTÁ A CORREÇÃO: O bloco 'env' injeta os secrets
      # que você cadastrou no GitHub como variáveis de ambiente
      # durante o processo de 'npm run build'.
      - name: Build Project
        run: npm ci && npm run build
        env:
          VITE_FIREBASE_APIKEY: ${{ secrets.VITE_FIREBASE_APIKEY }}
          VITE_FIREBASE_AUTHDOMAIN: ${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}
          VITE_FIREBASE_PROJECTID: ${{ secrets.VITE_FIREBASE_PROJECTID }}
          VITE_FIREBASE_STORAGEBUCKET: ${{ secrets.VITE_FIREBASE_STORAGEBUCKET }}
          VITE_FIREBASE_MESSAGINGSENDERID: ${{ secrets.VITE_FIREBASE_MESSAGINGSENDERID }}
          VITE_FIREBASE_APPID: ${{ secrets.VITE_FIREBASE_APPID }}

      # 3. Faz o deploy do conteúdo da pasta 'dist' (gerada pelo build) para o Firebase
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEU_APP_CALORIAS_V2 }}
          channelId: live
          projectId: meu-app-calorias-v2
